#!/usr/bin/env bash

sudo apt-get install python-pip
sudo pip install virtualenv
sudo virtualenv venv
source venv/bin/activate

sudo apt-get install mysql-server mysql-client
sudo apt-get install libmysqlclient-dev

sudo pip install -r flaskApp/requirements.txt